- name: Copying Service File
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Starting and Enabling {{ component }} Server
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon_reload: true