- name: Install mysql client
  ansible.builtin.yum:
    name: mysql
    state: latest

- name: Loading Schema
  ansible.builtin.shell: mysql -h mysql-dev.rkdevops.store -uroot -pRoboShop@1 < /app/schema/{{ component }}.sql